development:
  cloud_name: "dial2brux"
  api_key: "335962744686271"
  api_secret: "HMH6SFyjGOazEfuVqimg7PyGfuA"
  secure: true

production:
  cloud_name: "dial2brux"
  api_key: "335962744686271"
  api_secret: "HMH6SFyjGOazEfuVqimg7PyGfuA"
  secure: true
